"""empty message

Revision ID: 007f6ebdf9d3
Revises: 73c8e86d2884
Create Date: 2021-08-23 14:36:53.670907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007f6ebdf9d3'
down_revision = '73c8e86d2884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'commentary',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint('products_sizes_size_id_fkey', 'products_sizes', type_='foreignkey')
    op.drop_constraint('products_sizes_product_id_fkey', 'products_sizes', type_='foreignkey')
    op.create_foreign_key(None, 'products_sizes', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products_sizes', 'sizes', ['size_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_sizes', type_='foreignkey')
    op.drop_constraint(None, 'products_sizes', type_='foreignkey')
    op.create_foreign_key('products_sizes_product_id_fkey', 'products_sizes', 'products', ['product_id'], ['id'])
    op.create_foreign_key('products_sizes_size_id_fkey', 'products_sizes', 'sizes', ['size_id'], ['id'])
    op.alter_column('orders', 'commentary',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
