"""empty message

Revision ID: 73c8e86d2884
Revises: f79e1ac86657
Create Date: 2021-08-23 14:14:07.693135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73c8e86d2884'
down_revision = 'f79e1ac86657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('commentary', sa.String(length=120), nullable=False),
    sa.Column('items', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cart', 'product_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'product_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_table('orders')
    # ### end Alembic commands ###
