"""empty message

Revision ID: 863a667eb390
Revises: b79a51bf5289
Create Date: 2021-09-06 12:54:50.222234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863a667eb390'
down_revision = 'b79a51bf5289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_carts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_carts',
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='products_carts_cart_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='products_carts_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id', name='products_carts_pkey')
    )
    # ### end Alembic commands ###
