"""empty message

Revision ID: 9487eb155c96
Revises: 007f6ebdf9d3
Create Date: 2021-08-25 14:39:31.175107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9487eb155c96'
down_revision = '007f6ebdf9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('state', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'date')
    op.drop_column('orders', 'state')
    # ### end Alembic commands ###
