"""empty message

Revision ID: b79a51bf5289
Revises: 1a0857202d85
Create Date: 2021-09-06 12:54:33.280289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79a51bf5289'
down_revision = '1a0857202d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_carts',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id')
    )
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'product_id')
    op.drop_table('products_carts')
    # ### end Alembic commands ###
