"""empty message

Revision ID: c2d716bdfb82
Revises: 5edb5b49610b
Create Date: 2021-09-06 12:26:34.437863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d716bdfb82'
down_revision = '5edb5b49610b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'product_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'product_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('cart', 'product_title')
    op.drop_column('cart', 'product_price')
    op.drop_column('cart', 'product_uuid')
    op.drop_column('cart', 'product_image')
    op.add_column('products', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'cart', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'cart_id')
    op.add_column('cart', sa.Column('product_image', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('product_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('product_title', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('cart', 'product_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'product_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
