"""empty message

Revision ID: f79e1ac86657
Revises: 06d573192bb8
Create Date: 2021-08-20 15:18:38.964947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79e1ac86657'
down_revision = '06d573192bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_uuid', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_uuid')
    # ### end Alembic commands ###
